# Site settings
baseURL = "https://shreyasalot.netlify.app/"
languageCode = "en-us"
title = "Shreya"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Shreya"
  description = "This is my portfoilio of projects that I have worked on recently using R. "

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Shreya"
    subtitle = "MFA 2021"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

    [[params.navigation.links]]
      name = "Generic Blog"
      url = "blogs/ipsum"

    [[params.navigation.links]]
      name = "Elements"
      url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Get Started"
      url = "blogs"

    # Button Style 2 
    [[params.navigation.button2]]
      name = "Log In"
      url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Shreya"
    subtitle = "This is my portfolio website."
    buttonText = "Get Started"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "About me"
      subtitle = "Who am I?"
      image = "pic08.jpg"
      url = "blogs/blog5"

    [[params.tiles.showcase]]
      title = "Climate Change"
      subtitle = "Lets look at data from NASA "
      image = "pic07.jpg"
      url = "blogs/blog6"

    [[params.tiles.showcase]]
      title = "IMDB Ratings"
      subtitle = "Lets look at ratings for directors"
      image = "pic09.jpg"
      url = "blogs/blog7"

    [[params.tiles.showcase]]
      title = "U.S. Yield Curve"
      subtitle = "Treasury Rates and Yield Curves"
      image = "pic010.jpg"
      url = "blogs/blog8"

    [[params.tiles.showcase]]
      title = "GDP by Country"
      subtitle = "Lets compare some countries"
      image = "pic011.jpg"
      url = "blogs/blog9"

    [[params.tiles.showcase]]
      title = "Etiam"
      subtitle = "Feugiat Amet Tempus"
      image = "pic06.jpg"
      url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "This Website"
    subtitle = """This website is my portfolio of some work that I have done in my Data Analytics Class. 
    I took this class from September to October 2020 as a student at London Business School. 
    I learnt how to install and work with R Markdown files. I also learnt how R is suitable to use when there is a large amount of data.
    It can be useful in calculations and plotting data easily as well. This is my first programming course and it has been very interesting."""
    buttonText = "Get Started"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "ssalot.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "(000) 7587-2**-***"

    [[params.contact.address]]
    title = "Address"
    street = "Regent's Park"
    city = "London, NW1 4SA"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Shreya Inc"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/ShreyaSalot"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/salot.shreya/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/shreyasalot/"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/shreya-salot-931298109/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
